# Use an official Node.js runtime as a parent image
FROM node:16-alpine

# Set the working directory to /app
WORKDIR /app


COPY package*.json ./


RUN npm install


COPY . .


RUN npm run build

# Use a smaller image for serving static files
FROM nginx:alpine


COPY --from=0 /app/dist /usr/share/nginx/html


EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]